// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// permInteractionCpp
arma::mat permInteractionCpp(const arma::mat& XY, const arma::ivec& g_XY, int n1, int n2, int B, int g1, int g2);
RcppExport SEXP _CrossAncestryGenPhen_permInteractionCpp(SEXP XYSEXP, SEXP g_XYSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP BSEXP, SEXP g1SEXP, SEXP g2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type XY(XYSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type g_XY(g_XYSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< int >::type g2(g2SEXP);
    rcpp_result_gen = Rcpp::wrap(permInteractionCpp(XY, g_XY, n1, n2, B, g1, g2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CrossAncestryGenPhen_permInteractionCpp", (DL_FUNC) &_CrossAncestryGenPhen_permInteractionCpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_CrossAncestryGenPhen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
