# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permInteractionCpp <- function(XY, g_XY, n1, n2, B, g1, g2) {
    .Call('_CrossAncestryGenPhen_permInteractionCpp', PACKAGE = 'CrossAncestryGenPhen', XY, g_XY, n1, n2, B, g1, g2)
}

